package Vistas;

import Controlador.GestionArchivos;
import Controlador.ListaAdya;
import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class Principal extends javax.swing.JFrame {

    JFileChooser seleccion = new JFileChooser();
    File archivo;
    GestionArchivos gestion;
    ListaAdya grafo;
    String[] palabras;

    public Principal() {
        initComponents();
        consola.setOpaque(false);
        consola.setBackground(new Color(0, 0, 0, 0));
        scrollPane.getViewport().setOpaque(false);
        scrollPane.setOpaque(false);
        panel2.setEnabled(false);
        //panel2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel1 = new javax.swing.JPanel();
        btnAbrir = new javax.swing.JButton();
        panel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        p2 = new javax.swing.JComboBox();
        p1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        btnCaminos = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        consola = new javax.swing.JTextArea();
        fondo = new javax.swing.JLabel();
        btnReinicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panel1.setBackground(new java.awt.Color(37, 37, 37));

        btnAbrir.setText("Abrir Archivo");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btnAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(554, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        panel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Palabra 2");
        panel2.add(jLabel1);
        jLabel1.setBounds(380, 90, 110, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("a la palabra 2.");
        panel2.add(jLabel4);
        jLabel4.setBounds(50, 40, 670, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Presione el botón para encontrar los caminos de la plabra 1");
        panel2.add(jLabel2);
        jLabel2.setBounds(50, 20, 670, 20);

        panel2.add(p2);
        p2.setBounds(490, 90, 100, 27);

        panel2.add(p1);
        p1.setBounds(180, 90, 100, 27);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Palabra 1");
        panel2.add(jLabel3);
        jLabel3.setBounds(60, 90, 120, 20);

        btnCaminos.setText("Caminos");
        btnCaminos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaminosActionPerformed(evt);
            }
        });
        panel2.add(btnCaminos);
        btnCaminos.setBounds(300, 140, 130, 30);

        consola.setEditable(false);
        consola.setColumns(20);
        consola.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        consola.setForeground(new java.awt.Color(255, 255, 255));
        consola.setRows(5);
        scrollPane.setViewportView(consola);

        panel2.add(scrollPane);
        scrollPane.setBounds(150, 200, 420, 180);

        fondo.setFocusable(false);
        panel2.add(fondo);
        fondo.setBounds(0, 0, 0, 430);

        btnReinicio.setText("Abrir otro archivo");
        btnReinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReinicioActionPerformed(evt);
            }
        });
        panel2.add(btnReinicio);
        btnReinicio.setBounds(530, 390, 140, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        if (seleccion.showDialog(null, "ABRIR ARCHIVO") == JFileChooser.APPROVE_OPTION) {
            archivo = seleccion.getSelectedFile();
            if (archivo.canRead()) {
                if (archivo.getName().endsWith(".txt")) {
                    btnAbrir.setEnabled(false);
                    try {
                        gestion = new GestionArchivos(archivo);
                        palabras = gestion.generarVector();
                        grafo = new ListaAdya(palabras);
                        llenarCombos();
                    } catch (Exception e) { //Catch de excepciones
                        System.err.println("Ocurrio un error: " + e.getMessage());
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Por favor seleccione un archivo de texto (.txt).");
                }
            }
        }
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnCaminosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaminosActionPerformed
        if (p1.getSelectedItem() != null) {
            ArrayList<String[]> caminos = grafo.caminos(p1.getSelectedItem().toString(), p2.getSelectedItem().toString());
            consola.setText("");
            consola.append("Caminos de " + p1.getSelectedItem().toString() + " a " + p2.getSelectedItem().toString() + "\n \n");
            if (caminos.size() == 0) {
                consola.append("No hay caminos entre estos vértices.");
            } else {
                String[] camino;
                int n, menor = caminos.get(0).length;
                for (int i = 0; i < caminos.size(); i++) {
                    camino = caminos.get(i);
                    consola.append("Camino " + (i + 1) + ": \n {");
                    n = camino.length;
                    if (n < menor) {
                        menor = n;
                    }
                    for (int j = 0; j < n; j++) {
                        consola.append(camino[j]);
                        if (j != n - 1) {
                            consola.append(" -> ");
                        } else {
                            consola.append("} \n");
                        }
                    }
                }
                consola.append("\n Camino(s) más corsto(s): \n");
                for (int i = 0; i < caminos.size(); i++) {
                    if (caminos.get(i).length == menor) {
                        consola.append("Camino " + (i + 1) + "\n");
                    }
                }
            }
        } else{
            consola.setText("No hay palabras para buscar camino");
        }
    }//GEN-LAST:event_btnCaminosActionPerformed

    private void btnReinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReinicioActionPerformed
        p1.removeAllItems();
        p2.removeAllItems();
    }//GEN-LAST:event_btnReinicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    public void llenarCombos() {
        for (int i = 0; i < palabras.length; i++) {
            p1.addItem(palabras[i]);
            p2.addItem(palabras[i]);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnCaminos;
    private javax.swing.JButton btnReinicio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea consola;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox p1;
    private javax.swing.JComboBox p2;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
